import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import  About_us  from './about-us';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home({data}) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
          <nav className={styles.header}>
            <img />
            <Link className={styles.header_link} href=''>Home</Link>
            <Link className={styles.header_link} href='/events'>Events</Link>
            <Link className={styles.header_link} href='/about-us'>About us</Link>
          </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev) => (
          <Link key={ev.id} href={`/events/${ev?.id}`} passHref>
            <Image width={200} height={150} alt={ev.title} src={ev.image} />
            <h2>{ev.title}</h2>
            <p>{ev.description}</p>
          </Link>
        ))}
      </main>
    </>
  )
}

export async function getServerSideProps() {
  // const data = await import('../data/data.json');
  //const res = await fetch('URL');
  //const data = await res.json();

  const {events_categories} = await import('../data/data.json');
  // console.log(events_categories)

  return {
      props: {
          data: events_categories
      }
  }
}